[project]
name = "py4e"
version = "1.7.0"
description = "The companion repository to the \"Python for Everybody\" book."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "ipywidgets>=8.1.6",
    "jupyterlab>=4.4.0",
    "lxml>=5.3.2",
]
